baseURL = 'https://hjkunst.github.io/'
languageCode = 'en-us'
title = 'Strawberry Fields'

theme = 'hugo-discaptive'

[params]
  useCDN = true
  customCSS = ['css/custom.css']
  mainSections = ['posts']
  favicon = '/favicon.svg'
  mathjax = true
  github = 'https://github.com/hjkunst'
  username = 'hjkunst'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[deployment]
  [[deployment.targets]]
    name = "github"
    URL = "github://hjkunst/hjkunst.github.io"

[build]
  writeStats = false
  buildFuture = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false

[menus]
[[menus.main]]
  name = 'About'
  url = '/about'
  weight = 1
[[menus.main]]
  name = 'Tags'
  url = '/tags'
  weight = 2

[pagination]
  pagerSize = 5  # Specify the max number of rows to be returned in list
