baseURL = 'https://hjkunst.github.io/'
title = 'Strawberry Fields — Pastoral Tech Notes by @lkkunst'

theme = 'hugo-discaptive'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageCode = 'en-us'
    languageName = 'ENG'
    weight = 1
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'About'
        url = '/about'
        weight = 1
      [[languages.en.menus.main]]
        name = 'Tags'
        url = '/tags'
        weight = 2
  [languages.ko]
    languageCode = 'ko-kr'
    languageName = 'KOR'
    weight = 2
    [languages.ko.menus]
      [[languages.ko.menus.main]]
        name = '소개'
        url = '/about'
        weight = 1
      [[languages.ko.menus.main]]
        name = '태그'
        url = '/tags'
        weight = 2

[params]
  useCDN = true
  customCSS = ['css/custom.css']
  mainSections = ['posts']
  favicon = '/favicon.svg'
  mathjax = true
  github = 'https://github.com/hjkunst'
  username = 'hjkunst'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[deployment]
  [[deployment.targets]]
    name = "github"
    URL = "github://hjkunst/hjkunst.github.io"

[build]
  writeStats = false
  buildFuture = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false

[pagination]
  pagerSize = 5
